### ISSUE TITLE
How to adapt pyoslc to another use case?

### ISSUE THREAD

**Issue by vicgb** [cslab/pyoslc#24]
Hi everyone.
I'm trying to use pyOSLC to make an OSLC adapter for Github, but I'm not really able to understand very well how to get pyoslc into practice. 
I don't know if I should modify the code to adapt it to my use case or import something specific functions or classes from the library, in a new Flask app.

Is there any documentation or example of a use case? 

Thanks in advance,

**Comment by fpatz** [comment]
You might want to take a look at the develop branch, where we are currently refactoring the code to make it easier to adapt to use cases like yours. We expect this to become ready in a few weeks time.

**Comment by isccarrasco** [comment]
Hi @vicgb

As Frank has mentioned, the new API design is in the `develop` branch. And for the implementation, you do not need to modify anything of the code within the PyOSLC project, in fact you have to implement your `Adapter` to interact with Github to get the information you want to expose through the OSLC API, the idea of using the `Adapter` is to delegate the tasks for accessing the information to the developer.

You can find an example of this approach within the [`apposlc`](https://github.com/cslab/pyoslc/tree/develop/apposlc) folder in which we illustrate the implementation of the adapter.

Regards!

**Comment by vicgb** [comment]
I'll take a look at the develop branch then and I will keep an eye on developments 

Thank you to both of you.
