### ISSUE TITLE
Hint? I am trying to create a configuration using Python and I run into the issue, how to create a special RDF tuple, have a hint?

### ISSUE THREAD

**Issue by rsjazz** [cslab/pyoslc#30]
Hi, I know this is asking a lot, but I try to create a configuration in Python. I am using rdflib to create the RDF. I am able to generate the most content. The only one that eludes me is related to rdf:parseType. To create:

<dcterms:title rdf:parseType="Literal">Title</dcterms:title>

I have looked into https://github.com/cslab/pyoslc/blob/e37d73c6e79b3fb4f9e935ff7b615894f3b8d461/pyoslc/serializers/configxml.py

and it seems to hint on 

    # Create the payload
    payload = comm.createRDFGraph()
    testItem = URIRef('https://elm.example.com:9443/qm/')
    title = 'Some Title'
    doc = xml.dom.minidom.Document()
    elem = doc.createElement('SomeTitle')
    doc.appendChild(elem)
    comm.createRDFAttribute(payload, testItem, DCTERMS.title, Literal(doc))
  
The last line translates to 
payload.add((node, testItem, DCTERMS.title, Literal(doc)))

Unfortunately that creates 

<dcterms:title rdf:datatype="http://www.w3.org/1999/02/22-rdf-syntax-ns#XMLLiteral">&lt;SomeTitle/&gt;</dcterms:title>

If you could provide me a hint, that would be really appreciated.

**Comment by isccarrasco** [comment]
Hi @rsjazz,

For having the format like: 
```xml
<dcterms:title rdf:parseType="Literal">Your Title Here</dcterms:title>
```
in which we have the `rdf:parseType` just with the `Literal` value we normally use the following format:

Given a graph,
```python
from rdflib import Graph, URIRef, Literal, XSD
from rdflib.resource import Resource
from rdflib.namespace import DCTERMS

graph = Graph()
```

we create a Resource like:
```python
resource = Resource(graph, URIRef('https://elm.example.com:9443/qm/'))
```

so, for defining the `title` as a `Literal` we do:
```python
resource.add(DCTERMS.title, Literal('Your Title Here', datatype=XSD.string))
```

Hope this could help in your implementation

Sorry for the late reply.

**Comment by rsjazz** [comment]
Thank you so much @isccarrasco. Don't worry, I am so glad you answered. This works for me!
I think I can take it from here. If I get myself into trouble again, may I ask again?

**Comment by isccarrasco** [comment]
For sure @rsjazz, I’ll be happy to help!
