### ISSUE TITLE
AttributeError: can't set attribute

### ISSUE THREAD

**Issue by vicgb** [cslab/pyoslc#31]
Hi everyone. 

I'm trying to execute the pyoslc demo by following the README steps and this is what I get:

_'AttributeError: can't set attribute'_ on ../pyoslc_server/cli.py in load_app 
_app.debug = get_debug_flag()_

On my .pyoslcenv I've written:

PYOSLC_APP=apposlc.wsgi:app
PYOSLC_ENV=development
PYOSLC_DEBUG=False (also tried with True)

Any help?

Thanks in advance.

**Comment by isccarrasco** [comment]
Hello @vicgb.

I just merged a new update to the develop branch that solve this and other issues, please reinstall the library on your environment to avoid this message when running your application.

Regards!
