### ISSUE TITLE
Setup GH actions for packaging on PyPI

### ISSUE THREAD

**Issue by isccarrasco** [cslab/pyoslc#7]
Generate the actions to build the package and sent the packages to PyPI.

**Comment by isccarrasco** [comment]
Hi @fpatz, can you please add the secrets for the PyPI account to use with twine library for uploading the package? 

or can you give the access to the secret sections to configure my credential for the [test.pypi.org](https://test.pypi.org), then we can change to the real credentials.

Regards!

**Comment by fpatz** [comment]
Hi Mario, I gave you Admin access. Will be back at work on Monday.

**Comment by isccarrasco** [comment]
The packaging is prepared to upload the project to the PyPI, it only requires to update the credentials on the secrets section.
